# Generated by Django 5.2.8 on 2025-11-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_stream',
            field=models.BooleanField(default=False, verbose_name='Pode criar stream'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_stream',
            field=models.BooleanField(default=False, verbose_name='Pode deletar stream'),
        ),
    ]
