# Generated by Django 5.2.8 on 2025-11-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_can_create_stream_user_can_delete_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Válido até'),
        ),
    ]
