# Generated by Django 5.2.8 on 2025-11-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('ENDED', 'Ended')], default='UPCOMING', max_length=10),
        ),
    ]
