# Generated by Django 5.2.8 on 2026-09-07 23:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('host', 'Host'), ('viewer', 'Viewer')], max_length=6)),
                ('ready', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='streams.streamroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(unique=True)),
                ('connection_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to='streams.streamparticipant')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to='streams.streamparticipant')),
            ],
            options={
                'indexes': [models.Index(fields=['target', 'id'], name='stream_signal_target_id')],
            },
        ),
    ]
